---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Set AWS credentials as environment variables
      shell: |
        export AWS_ACCESS_KEY_ID=your_access_key
        export AWS_SECRET_ACCESS_KEY=your_secret_key
        export AWS_DEFAULT_REGION=your_region
        
    - name: Stop EC2 instance
      amazon.aws.ec2:
        instance_ids: your_instance_id
        state: stopped
        region: us-west-1

