---
- name: Provision VM
  hosts: localhost
  gather_facts: yes
  tasks:
    -  name: Set connection based on os type
       set_fact:
         connection_type: "{{ ansible_os_family }}"

    - name: Debug connection type
      debug:
        msg: "Connection type is {{ connection_type }}"
        
    - name: Set connection based on os type (Debian)
      set_fact:
        ansible_connection: "Debian"
      when: '"Debian" in connection_type'

    - name: Set connection based on os type (Debian)
      set_fact:
        ansible_connection: "Debian"
      when: '"RedHat" not in connection_type'
