name: My First GitHub Actions Demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get remove --purge containerd.io containerd
        sudo apt-get clean
        sudo apt-get autoremove -y
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -f
        sudo apt-get install -y docker.io ansible
        python -m pip install --upgrade pip
        docker pull ubuntu:20.04
        echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        docker build -t my-app .
        docker tag my-app:latest my-docker-image:latest
        docker push my-docker-image:latest
        ansible-galaxy collection install amazon.aws
        pip install pytest pywinrm
        
    - name: Build and push Docker image
      run: |
        docker build -t my-hotel-app .
        docker tag my-hotel-app:latest my-docker-image:latest
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push my-docker-image:latest
        
    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Run Bash script
      run: |
        # Replace placeholders with actual values
        region="us-east-1"
        instanceId="i-0123456789abcdef0"

        # Get the status of the EC2 instance
        instanceStatus=$(aws ec2 describe-instance-status --instance-id $instanceId --region $region --query 'InstanceStatuses[*].InstanceState.Name' --output text)

        echo "The status of the EC2 instance is: $instanceStatus"
        
    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
