name: My First GitHub Actions Demo

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pwd
        touch pradip1.txt
        sudo apt-mark unhold containerd.io containerd || true
        sudo apt-get remove --purge containerd.io containerd -y
        sudo apt-get clean
        sudo apt-get autoremove -y
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -f
        sudo apt-get install -y docker.io ansible
        python -m pip install --upgrade pip
        pip install pytest pywinrm
        ansible-galaxy collection install amazon.aws
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: 'latest'
        driver: docker

    - name: Verify Minikube
      run: kubectl get pods -A

    - name: Build Docker image
      run: minikube image build -t local/my-app:latest .

    - name: Deploy to Minikube
      run: kubectl apply -f example/deployment.yaml

    - name: Wait for deployment
      run: kubectl rollout status deployment/my-app

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      run: |
        docker pull ubuntu:20.04
        mkdir -p ${{ github.workspace }}/docker-images
        docker save ubuntu:20.04 -o ${{ github.workspace }}/docker-images/ubuntu-20.04.tar      

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        cd src
        ansible-playbook vm-provisioning.yml
        
  artifactory:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Save artifacts
      run: |
        mkdir -p src/artifacts
        cp src/artifacts/* src/artifacts/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: src/artifacts/

  shell-module:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - uses: actions/checkout@v3
    - name: Execute Linux commands
      run: |
        echo "Running custom shell commands"
        touch pradip1.txt
        echo "This is the text to append" >> pradip1.txt
        echo "dgwgen79876" >> pradip1.txt
        cat pradip1.txt
        # Add your custom shell commands here
        ls -la
        uname -a
