name: My First GitHub Actions demo see

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install python-dev libkrb5-dev
        pip install pywinrm
        pip install kerberos
        pip install pytest
        sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install krb5-user
        
    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
