name: My First GitHub Actions demo see

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
            
    - script: sudo apt-get install python-dev libkrb5-dev
       displayName: "Install Kerberos libraries"
    - script: pip install pywinrm
       displayName: "Install WinRM module"
    - script: pip install kerberos
       displayName: "Install Kerberos module"
    - script: sudo DEBIAN_FRONTEND=noninteractive apt-get -yq install krb5-user
       displayName: "Installing Kerberos Authentication Pre-requisites"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
