name: My First GitHub Actions demo see what

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt install openjdk-11-jdk
        sudo pip3 install ansible
        pip install pytest
        sudo apt install ansible
        pip install pywinrm
        
    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
