name: My First GitHub Actions Demo

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-mark unhold containerd.io containerd || true
        sudo apt-get remove --purge containerd.io containerd -y
        sudo apt-get clean
        sudo apt-get autoremove -y
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest
      with:
        minikube-version: 'latest'
        driver: docker
        
    - name: Set up Docker environment for Minikube
      run: eval $(minikube -p minikube docker-env)

    - name: Build Docker image
      run: docker build -t local/node-app:latest .

    - name: Verify Docker image
      run: docker images | grep node-app

    - name: Deploy to Minikube
      run: kubectl apply -f examples/deploy-to-k8s.yml
      
    - name: Get Minikube IP
      run: minikube ip
      
    - name: Port Forward
      run: |
        nohup kubectl port-forward service/node-app-service 3000:3000 &
        sleep 10 # Give port-forwarding some time to establish

    - name: Wait for deployment
      run: |
        # Check the status of all pods
        kubectl get pods -l app=node-app

        # Describe a specific pod
        POD_NAME=$(kubectl get pods -o jsonpath='{.items[0].metadata.name}')

        # Check deployment events
        kubectl describe deployment node-app-deployment

        # Check logs of a specific pod
        kubectl rollout status deployment/node-app-deployment
